/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Reprezentacija;
import domen.Utakmica;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import konstante.Operacije;
import logika.KomunikacijaSaServerom;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Bron Zilar
 */
public class IzmenaUtakmice extends javax.swing.JDialog {

    Utakmica izabranaUtakmica;
    /**
     * Creates new form IzmenaUtakmice
     */
    public IzmenaUtakmice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        napuniComboBoxove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtGrupa = new javax.swing.JTextField();
        jtxtGoloviDomacin = new javax.swing.JTextField();
        jtxtGoloviGost = new javax.swing.JTextField();
        jbtnZapamtiIzmene = new javax.swing.JButton();
        jcmbDomacin = new javax.swing.JComboBox();
        jcmbGost = new javax.swing.JComboBox();
        jbtnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Grupa");

        jLabel2.setText("Domacin");

        jLabel3.setText("gost");

        jLabel4.setText("Golovi domacin");

        jLabel5.setText("Golovi gost");

        jbtnZapamtiIzmene.setText("Zapamti izmene");
        jbtnZapamtiIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiIzmeneActionPerformed(evt);
            }
        });

        jcmbDomacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcmbGost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnZapamtiIzmene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIzadji))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtGrupa)
                            .addComponent(jtxtGoloviDomacin)
                            .addComponent(jtxtGoloviGost)
                            .addComponent(jcmbDomacin, 0, 334, Short.MAX_VALUE)
                            .addComponent(jcmbGost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbDomacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtGoloviDomacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtGoloviGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnZapamtiIzmene)
                    .addComponent(jbtnIzadji))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnZapamtiIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiIzmeneActionPerformed
        String grupa = jtxtGrupa.getText();
        int goloviDomacin = Integer.parseInt(jtxtGoloviDomacin.getText().trim());
        int golovaGost = Integer.parseInt(jtxtGoloviGost.getText().trim());
        Reprezentacija domacin = (Reprezentacija) jcmbDomacin.getSelectedItem();
        Reprezentacija gost = (Reprezentacija) jcmbGost.getSelectedItem();
        
        Utakmica u = new Utakmica(izabranaUtakmica.getUtakmicaID(), grupa, domacin, gost, goloviDomacin, golovaGost, "izmena");
        
        boolean ubaceno = ((KlijentskaForma)this.getParent()).dodajIzmenjenuUtakmicu(u);
        
        if(ubaceno) {
            JOptionPane.showMessageDialog(this, "Uspesno sacuvane izmene");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno sacuvane izmene", "greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnZapamtiIzmeneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmenaUtakmice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmenaUtakmice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmenaUtakmice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmenaUtakmice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmenaUtakmice dialog = new IzmenaUtakmice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnZapamtiIzmene;
    private javax.swing.JComboBox jcmbDomacin;
    private javax.swing.JComboBox jcmbGost;
    private javax.swing.JTextField jtxtGoloviDomacin;
    private javax.swing.JTextField jtxtGoloviGost;
    private javax.swing.JTextField jtxtGrupa;
    // End of variables declaration//GEN-END:variables

    private void napuniComboBoxove() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_REPREZENTACIJE);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<Reprezentacija> lista = (ArrayList<Reprezentacija>) so.getOdgovor();
        
        jcmbDomacin.removeAllItems();
        for (Reprezentacija reprezentacija : lista) {
            jcmbDomacin.addItem(reprezentacija);
        }
        
        jcmbGost.removeAllItems();
        for (Reprezentacija reprezentacija : lista) {
            jcmbGost.addItem(reprezentacija);
        }
    }

    void srediUtakmicu(Utakmica u) {
        this.izabranaUtakmica = u;
        jtxtGrupa.setText(u.getGrupa());
        jcmbDomacin.setSelectedItem(u.getDomacin());
        System.out.println(u.getDomacin());
        jcmbGost.setSelectedItem(u.getGost());
        System.out.println(u.getGost());
        jtxtGoloviDomacin.setText((String.valueOf(u.getBrojGlovaDomacina())));
        jtxtGoloviGost.setText(String.valueOf(u.getBrojGolovaGost()));
    }
}
