/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fomre;

import domen.StavkaKursneListe;
import domen.Zemlja;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import konstante.Operacije;
import logika.Komunikacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Bron Zilar
 */
public class UbaciStavku extends javax.swing.JDialog {

    /**
     * Creates new form UbaciStavku
     */
    public UbaciStavku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbZemlja = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtVaziZa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtKupovni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtProdajni = new javax.swing.JTextField();
        jbtnSacuvajStavku = new javax.swing.JButton();
        jtbnotkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Zemlja");

        jcmbZemlja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Vazi za");

        jLabel3.setText("kupovni");

        jLabel4.setText("Prodajni");

        jbtnSacuvajStavku.setText("Scuvaj stavku");
        jbtnSacuvajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajStavkuActionPerformed(evt);
            }
        });

        jtbnotkazi.setText("Otkazi");
        jtbnotkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnotkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcmbZemlja, 0, 255, Short.MAX_VALUE)
                            .addComponent(jtxtVaziZa)
                            .addComponent(jtxtKupovni)
                            .addComponent(jtxtProdajni)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jbtnSacuvajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jtbnotkazi)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbZemlja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtVaziZa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtKupovni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtProdajni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvajStavku)
                    .addComponent(jtbnotkazi))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbnotkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnotkaziActionPerformed
        dispose();
    }//GEN-LAST:event_jtbnotkaziActionPerformed

    private void jbtnSacuvajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajStavkuActionPerformed
        if(jtxtKupovni.getText().isEmpty() || jtxtProdajni.getText().isEmpty() || jtxtVaziZa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ne mogu prazna polja");
            return;
        }
        double kupovni = Double.parseDouble(jtxtKupovni.getText().trim());
        double prodajni = Double.parseDouble(jtxtProdajni.getText().trim());
        int vaziZa = Integer.parseInt(jtxtVaziZa.getText().trim());
        
        if(kupovni > prodajni) {
            JOptionPane.showMessageDialog(this, "Kupovni mora biti manji od prodajnog");
            return;
        }
        if(kupovni*1.05<prodajni) {
            JOptionPane.showMessageDialog(this, "Problem 5%");
            return;
        }
        if(kupovni<=0 || prodajni<=0) {
            JOptionPane.showMessageDialog(this, "Moraju biti veci od nule");
            return;
        }
        Zemlja zemlja = (Zemlja) jcmbZemlja.getSelectedItem();
        double srednji = (kupovni+prodajni)/2d;
        StavkaKursneListe stavka = new StavkaKursneListe(-1, zemlja, vaziZa, kupovni, srednji, prodajni);
        
        KlijentskaForma kf = (KlijentskaForma) getParent();
        kf.dodajStavku(stavka);
    }//GEN-LAST:event_jbtnSacuvajStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbaciStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbaciStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbaciStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbaciStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UbaciStavku dialog = new UbaciStavku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnSacuvajStavku;
    private javax.swing.JComboBox jcmbZemlja;
    private javax.swing.JButton jtbnotkazi;
    private javax.swing.JTextField jtxtKupovni;
    private javax.swing.JTextField jtxtProdajni;
    private javax.swing.JTextField jtxtVaziZa;
    // End of variables declaration//GEN-END:variables

    private void srediCombo() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_ZEMLJE);
        Komunikacija.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstanca().primiOdgovor();
        ArrayList<Zemlja> lista = (ArrayList<Zemlja>) so.getOdgovor();
        jcmbZemlja.removeAllItems();
        for (Zemlja zemlja : lista) {
            jcmbZemlja.addItem(zemlja);
        }
    }
}
