/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Prevod;
import domen.Rec;
import domen.Recnik;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import konstante.Operacije;
import logika.KomunikacijaSaServerom;
import modeli.ModelTabele;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Bron Zilar
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        sredicombo();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbRecnik = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtRec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcmbNaZezik = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtxtprevod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrevodi = new javax.swing.JTable();
        jbtnDodaj = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recnik");

        jcmbRecnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Rec");

        jLabel3.setText("Na jezik");

        jcmbNaZezik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Prevod");

        jtblPrevodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrevodi);

        jbtnDodaj.setText("Dodaj");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSacuvaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnDodaj)
                                    .addGap(43, 43, 43)
                                    .addComponent(jbtnObrisi))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcmbRecnik, 0, 361, Short.MAX_VALUE)
                                        .addComponent(jtxtRec)
                                        .addComponent(jcmbNaZezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtprevod)))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbRecnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcmbNaZezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtprevod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvaj)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        Recnik recnik = (Recnik) jcmbRecnik.getSelectedItem();
        String rec = jtxtRec.getText().trim();
        Recnik naJezik = (Recnik) jcmbNaZezik.getSelectedItem();
        String prevd = jtxtprevod.getText().trim();
        
        Rec r = new Rec(-1, rec, recnik, null);
        Prevod p = new Prevod(-1, prevd, recnik, naJezik,r);
        ModelTabele mt = (ModelTabele) jtblPrevodi.getModel();
        mt.dodajprevod(p);
        
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblPrevodi.getSelectedRow();
         ModelTabele mt = (ModelTabele) jtblPrevodi.getModel();
        if(red != -1) {
            mt.obrisiPrevod(red);
        } else {
            JOptionPane.showMessageDialog(this, "Morate selektovati red");
            return;
        }
       
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        /*Recnik saJezika = (Recnik) jcmbRecnik.getSelectedItem();
        String rec = jtxtRec.getText().trim();
        Recnik naJezik = (Recnik) jcmbRecnik.getSelectedItem();
        ModelTabele mt = (ModelTabele) jtblPrevodi.getModel();
        ArrayList<Prevod> prevodi = mt.getLista();
        if((jtxtRec.getText().isEmpty() || jtxtprevod.getText().isEmpty()) && prevodi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena");
            return;
        }
        if(prevodi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mora biti unet bar jedan prevod");
            return;
        }
        
        Rec r = new Rec(-1, rec, saJezika, prevodi);
        
        KlijentskiZahtev kz =new KlijentskiZahtev();
        kz.setOperacija(Operacije.SACUVAJ);
        kz.setParametar(r);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        JOptionPane.showMessageDialog(this, so.getPoruka());*/
        
        ArrayList<Rec> reci = new ArrayList<>();
        ModelTabele mt = (ModelTabele) jtblPrevodi.getModel();
        ArrayList<Prevod> prevodi = mt.getLista();
        for (Prevod prevod : prevodi) {
            if(!reci.contains(prevod.getRec())) {
                reci.add(prevod.getRec());               
            }
        }
        for(Rec rec : reci) {
            ArrayList<Prevod> prevodiNovi = new ArrayList<>();
            for (Prevod prevod : prevodi) {
                if(rec.equals(prevod.getRec())) {
                    prevodiNovi.add(prevod);
                }
            }
            rec.setPrevodi(prevodiNovi);
        }
        KlijentskiZahtev kz =new KlijentskiZahtev();
        kz.setOperacija(Operacije.SACUVAJ_VOL2);
        kz.setParametar(reci);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        JOptionPane.showMessageDialog(this, so.getPoruka());
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcmbNaZezik;
    private javax.swing.JComboBox jcmbRecnik;
    private javax.swing.JTable jtblPrevodi;
    private javax.swing.JTextField jtxtRec;
    private javax.swing.JTextField jtxtprevod;
    // End of variables declaration//GEN-END:variables

    private void sredicombo() {
        KlijentskiZahtev kz1 = new KlijentskiZahtev();
        kz1.setOperacija(Operacije.VRATI_RECNIKE);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz1);
        ServerskiOdgovor so1 = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<Recnik> lista1 = (ArrayList<Recnik>) so1.getOdgovor();
        
        jcmbRecnik.removeAllItems();
        for (Recnik recnik : lista1) {
            jcmbRecnik.addItem(recnik);
        }

        
        jcmbNaZezik.removeAllItems();
        for (Recnik recnik : lista1) {
            jcmbNaZezik.addItem(recnik);
        }
    }

    private void srediTabelu() {
        ModelTabele mt = new ModelTabele();
        jtblPrevodi.setModel(mt);
    }

    

    
}
