/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.PoreskaPrijava;
import domen.PoreskiInspektor;
import domen.PoreskiObveznik;
import domen.StavkaPoreskePrijave;
import domen.VrstaPoreza;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import konstante.Operacije;
import logika.KomunikacijaSaServerom;
import medeli.ModelTabele;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Bron Zilar
 */
public class KlijentskaForma extends javax.swing.JFrame {

    PoreskiInspektor inspektor;
    
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(PoreskiInspektor inspektor) {
        initComponents();
        srediFormu();
        this.inspektor=inspektor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbVrstaPoreza = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcmbPoreskiObveznik = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtxtGodina = new javax.swing.JTextField();
        jbtnDodajStavku = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabela = new javax.swing.JTable();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vrsta poreza");

        jcmbVrstaPoreza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Poreski obveznik");

        jcmbPoreskiObveznik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Godina");

        jbtnDodajStavku.setText("Dodaj stavku");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setText("Obrisi stavku");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        jtblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblTabela);

        jbtnSacuvaj.setText("Sacuvaj poresku prijavu");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDodajStavku)
                        .addGap(55, 55, 55)
                        .addComponent(jbtnObrisiStavku))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcmbVrstaPoreza, 0, 369, Short.MAX_VALUE)
                                    .addComponent(jtxtGodina)
                                    .addComponent(jcmbPoreskiObveznik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbVrstaPoreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbPoreskiObveznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajStavku)
                    .addComponent(jbtnObrisiStavku))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSacuvaj)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed
        VrstaPoreza vp = (VrstaPoreza) jcmbVrstaPoreza.getSelectedItem();
        JDialog forma = new FStavka(this, true, vp);
        forma.setVisible(true);
        
    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        if(jtxtGodina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
        }
        ModelTabele mt = (ModelTabele) jtblTabela.getModel();
        if(mt.getLista().size()<1) {
            JOptionPane.showMessageDialog(this, "Poreska prijava mora sadrzati bar jednu stavku");
            return;
        }
        
        int godina = Integer.parseInt(jtxtGodina.getText().trim());
        PoreskiObveznik obveznik = (PoreskiObveznik) jcmbPoreskiObveznik.getSelectedItem();
        ArrayList<StavkaPoreskePrijave> stavke = mt.getLista();
        PoreskaPrijava prijava = new PoreskaPrijava(-1, godina, obveznik, inspektor, stavke);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.SACUVAJ_PORESKU_PRIJAVU);
        kz.setParametar(prijava);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        JOptionPane.showMessageDialog(this, so.getPoruka());
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        int red = jtblTabela.getSelectedRow();
        ModelTabele mt = (ModelTabele) jtblTabela.getModel();
        if(red!=-1) {
            mt.obrisiStavku(red);
        } else {
            JOptionPane.showMessageDialog(this, "Morate selektovati red");
            return;
        }
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcmbPoreskiObveznik;
    private javax.swing.JComboBox jcmbVrstaPoreza;
    private javax.swing.JTable jtblTabela;
    private javax.swing.JTextField jtxtGodina;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        KlijentskiZahtev kz1 = new KlijentskiZahtev();
        kz1.setOperacija(Operacije.VRATI_VRSTE_POREZA);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz1);
        ServerskiOdgovor so1 = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<VrstaPoreza> vrstePoreza = (ArrayList<VrstaPoreza>) so1.getOdgovor();
        jcmbVrstaPoreza.removeAllItems();
        for (VrstaPoreza vrstaPoreza : vrstePoreza) {
            jcmbVrstaPoreza.addItem(vrstaPoreza);
        }
        
        KlijentskiZahtev kz2 = new KlijentskiZahtev();
        kz2.setOperacija(Operacije.VRATI_PORESKE_OBVEZNIKE);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz2);
        ServerskiOdgovor so2 = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<PoreskiObveznik> obveznici = (ArrayList<PoreskiObveznik>) so2.getOdgovor();
        jcmbPoreskiObveznik.removeAllItems();
        for (PoreskiObveznik poreskiObveznik : obveznici) {
            jcmbPoreskiObveznik.addItem(poreskiObveznik);
        }
        
        ModelTabele mt = new ModelTabele();
        jtblTabela.setModel(mt);
    }

    public JTable getJtblTabela() {
        return jtblTabela;
    }
    
    
}
